# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux
os: linux

files:
  - source: /
    destination: /usr/share/html

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # During the ApplicationStart deployment lifecycle event, run the commands
  #   in the script specified in "location".
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 301
      runas: root
