version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 301
      runas: root
