version: 0.2
phases:
  pre_build:
    commands:
      #installs dependencies for the code
      - yarn install
  build:
    commands:
    # builds a code in a folder called dist
      - yarn build
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
